<template>
    <div class="card mt-5">
        <div class="overlay" v-if="loading">
            <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" style="margin: auto; background: rgb(255, 255, 255); display: block; shape-rendering: auto;" width="200px" height="200px" viewBox="0 0 100 100" preserveAspectRatio="xMidYMid">
                <g transform="rotate(0 50 50)">
                    <rect x="47" y="24" rx="3" ry="6" width="6" height="12" fill="#fe718d">
                        <animate attributeName="opacity" values="1;0" keyTimes="0;1" dur="1s" begin="-0.9166666666666666s" repeatCount="indefinite"></animate>
                    </rect>
                </g><g transform="rotate(30 50 50)">
                <rect x="47" y="24" rx="3" ry="6" width="6" height="12" fill="#fe718d">
                    <animate attributeName="opacity" values="1;0" keyTimes="0;1" dur="1s" begin="-0.8333333333333334s" repeatCount="indefinite"></animate>
                </rect>
            </g><g transform="rotate(60 50 50)">
                <rect x="47" y="24" rx="3" ry="6" width="6" height="12" fill="#fe718d">
                    <animate attributeName="opacity" values="1;0" keyTimes="0;1" dur="1s" begin="-0.75s" repeatCount="indefinite"></animate>
                </rect>
            </g><g transform="rotate(90 50 50)">
                <rect x="47" y="24" rx="3" ry="6" width="6" height="12" fill="#fe718d">
                    <animate attributeName="opacity" values="1;0" keyTimes="0;1" dur="1s" begin="-0.6666666666666666s" repeatCount="indefinite"></animate>
                </rect>
            </g><g transform="rotate(120 50 50)">
                <rect x="47" y="24" rx="3" ry="6" width="6" height="12" fill="#fe718d">
                    <animate attributeName="opacity" values="1;0" keyTimes="0;1" dur="1s" begin="-0.5833333333333334s" repeatCount="indefinite"></animate>
                </rect>
            </g><g transform="rotate(150 50 50)">
                <rect x="47" y="24" rx="3" ry="6" width="6" height="12" fill="#fe718d">
                    <animate attributeName="opacity" values="1;0" keyTimes="0;1" dur="1s" begin="-0.5s" repeatCount="indefinite"></animate>
                </rect>
            </g><g transform="rotate(180 50 50)">
                <rect x="47" y="24" rx="3" ry="6" width="6" height="12" fill="#fe718d">
                    <animate attributeName="opacity" values="1;0" keyTimes="0;1" dur="1s" begin="-0.4166666666666667s" repeatCount="indefinite"></animate>
                </rect>
            </g><g transform="rotate(210 50 50)">
                <rect x="47" y="24" rx="3" ry="6" width="6" height="12" fill="#fe718d">
                    <animate attributeName="opacity" values="1;0" keyTimes="0;1" dur="1s" begin="-0.3333333333333333s" repeatCount="indefinite"></animate>
                </rect>
            </g><g transform="rotate(240 50 50)">
                <rect x="47" y="24" rx="3" ry="6" width="6" height="12" fill="#fe718d">
                    <animate attributeName="opacity" values="1;0" keyTimes="0;1" dur="1s" begin="-0.25s" repeatCount="indefinite"></animate>
                </rect>
            </g><g transform="rotate(270 50 50)">
                <rect x="47" y="24" rx="3" ry="6" width="6" height="12" fill="#fe718d">
                    <animate attributeName="opacity" values="1;0" keyTimes="0;1" dur="1s" begin="-0.16666666666666666s" repeatCount="indefinite"></animate>
                </rect>
            </g><g transform="rotate(300 50 50)">
                <rect x="47" y="24" rx="3" ry="6" width="6" height="12" fill="#fe718d">
                    <animate attributeName="opacity" values="1;0" keyTimes="0;1" dur="1s" begin="-0.08333333333333333s" repeatCount="indefinite"></animate>
                </rect>
            </g><g transform="rotate(330 50 50)">
                <rect x="47" y="24" rx="3" ry="6" width="6" height="12" fill="#fe718d">
                    <animate attributeName="opacity" values="1;0" keyTimes="0;1" dur="1s" begin="0s" repeatCount="indefinite"></animate>
                </rect>
            </g>
                <!-- [ldio] generated by https://loading.io/ --></svg>
        </div>
        <div class="card-body">
            <h5 class="card-title">Показатели</h5>
            <table class="table">
                <template v-for="item  in  group">
                    <tr class="thead-light">
                        <th colspan="3">Данные за: {{item.date | moment("LL")}}</th>
                    </tr>
                    <tr v-for="action in item.data">
                        <template v-for="(i, k) in action">
                            <td v-if="k !== 'id'">{{i}}</td>
                        </template>
                    </tr>
                </template>
            </table>
            <pagination :data="products" :limit="2" @pagination-change-page="paginate($event)">
                <span slot="prev-nav">&lt; Назад</span>
                <span slot="next-nav">Вперед &gt;</span>
            </pagination>
        </div>


    </div>
</template>
<script>
    import pagination from 'laravel-vue-pagination';
    export default {
        props: ['flag'],
        components: {
            pagination
        },
        data() {
            return {
                loading: false,
                products: {},
                queryParams: this.getQueryParams()
            }
        },
        computed: {
            group() {
                if (this.products.hasOwnProperty('data')) {
                    return this.products.data.reduce((accumulator, currentValue) => {
                        const index = accumulator.findIndex(i => i.date === currentValue.date);
                        if (index >= 0) {
                            accumulator[index].data.push(currentValue)
                            return accumulator
                        }
                        return [...accumulator, {date: currentValue.date, data: [currentValue]}]
                    }, [])
                }
                return []
            }
        },
        methods: {
            paginate(page) {
                console.log(this.queryParams)
                this.queryParams = {...this.queryParams, page: page}
                window.location.search = Object.entries(JSON.parse(JSON.stringify(this.queryParams))).map(i => {
                    return i.join('=')
                }).join('&')
            },
            getQueryParams() {
                if (!window.location.search) { return {} }
                return window.location.search.substring(1).split('&')
                    .map(i => {
                        const key = i.split('=')[0];
                        const value = i.split('=')[1];
                        return  { [key]: value }
                    }).reduce((acc, current) => {
                        return {...acc, ...current}
                    }, {});
            },
            loadData() {
                this.loading = true
                axios.get('/api/get', {
                    params: {...this.queryParams}
                })
                    .then(
                        response => {
                            this.products = response.data
                            this.loading = false
                        }
                    )
            }
        },
        watch: {
            flag() {
                this.loadData()
            }
        },
        mounted() {
            this.loadData()
        }
    }
</script>
<style scoped>
    .overlay {
        position: absolute;
        top: 0;
        bottom: 0;
        left: 0;
        right: 0;
        display: block;
        background-color: #fff;
        opacity: 0.5
    }
</style>
